source :rubygems

gem 'rails', '~> 3.2'

# Bundle edge Rails instead:
# gem 'rails', :git => 'git://github.com/rails/rails.git'

gem 'mongoid', '~> 2.4'
gem 'bson'

# gem 'mongoid', '~> 3.0.0.rc'
# gem 'moped'


gem 'devise', '~> 2.1'

gem 'netzke-core'

group :development, :test do
  gem 'capybara'
  gem 'cucumber-rails'
  gem 'cucumber'
  gem 'rspec-rails', ">= 2"
  gem 'spork'
  gem 'launchy'    # So you can do Then show me the page
  gem 'factory_girl'
end

group :development do
  # gem 'mysql2'
end

group :test do
  gem 'mongoid', '~> 2.4'
  gem 'bson'

  # gem 'mongoid', '~> 3.0.0.rc'
  # gem 'moped'

  gem 'pickle'

  # ensure use of version that also supports Mongoid 3+ (June 2012)
  gem 'database_cleaner', :git => 'git://github.com/bmabey/database_cleaner.git'
end
