source :rubygems

gem 'rails', '~> 3.2'
gem 'devise', '~> 2.1'

# Bundle edge Rails instead:
# gem 'rails', :git => 'git://github.com/rails/rails.git'

gem 'sqlite3-ruby', :require => 'sqlite3'
gem 'netzke-core', :git => 'git://github.com/nomadcoder/netzke-core.git'

# :development,
group  :test do
  gem 'capybara'
  gem 'cucumber-rails'
  gem 'cucumber'
  gem 'rspec-rails', ">= 2"
  gem 'spork'
  gem 'launchy'    # So you can do Then show me the page
  gem "factory_girl_rails", "~> 3.0"
end

group :development do
  gem 'mysql2'
end

group :test do
  gem 'sqlite3-ruby', :require => 'sqlite3'

  gem 'pickle'
  gem 'database_cleaner', '~> 0.7'
end
